name: Update Modules

on:
  repository_dispatch:
    types: update

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Update Submodules
        run: |
          git submodule update --init --recursive --checkout --remote -f
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git add .
      - name: Repo Generator
        run: python ./_repo_xml_generator.py
      - name: Commit packages
        run: |
          git add *.zip
          git commit -m ":package: - Update ${{github.event.client_payload.module}} to ${{github.event.client_payload.tag}}"
      - name: Commit meta files
        run: |
          git add .
          git commit -m ":bookmark: - Update metadata files"
          git push
